export const DIVISION_OPTIONS = [
  { id: "1", name: "Barishal", bn_name: "বরিশাল", lat: "22.701002", long: "90.353451" },
  { id: "2", name: "Chattogram", bn_name: "চট্টগ্রাম", lat: "22.356851", long: "91.783182" },
  { id: "3", name: "Dhaka", bn_name: "ঢাকা", lat: "23.810332", long: "90.412518" },
  { id: "4", name: "Khulna", bn_name: "খুলনা", lat: "22.845641", long: "89.540328" },
  { id: "5", name: "Rajshahi", bn_name: "রাজশাহী", lat: "24.363589", long: "88.624135" },
  { id: "6", name: "Rangpur", bn_name: "রংপুর", lat: "25.743892", long: "89.275227" },
  { id: "7", name: "Sylhet", bn_name: "সিলেট", lat: "24.894929", long: "91.868706" },
  { id: "8", name: "Mymensingh", bn_name: "ময়মনসিংহ", lat: "24.747149", long: "90.420273" }
]

export const DISTRICT_OPTIONS = [
  { id: "65", division_id: "3", name: "Dhaka City", bn_name: "ঢাকা শহর", lat: "23.7115253", long: "90.4111451" },
  { id: "1", division_id: "3", name: "Dhaka", bn_name: "ঢাকা", lat: "23.7115253", long: "90.4111451" },
  { id: "2", division_id: "3", name: "Faridpur", bn_name: "ফরিদপুর", lat: "23.6070822", long: "89.8429406" },
  { id: "3", division_id: "3", name: "Gazipur", bn_name: "গাজীপুর", lat: "24.0022858", long: "90.4264283" },
  { id: "4", division_id: "3", name: "Gopalganj", bn_name: "গোপালগঞ্জ", lat: "23.0050857", long: "89.8266059" },
  { id: "5", division_id: "8", name: "Jamalpur", bn_name: "জামালপুর", lat: "24.937533", long: "89.937775" },
  { id: "6", division_id: "8", name: "Kishoreganj", bn_name: "কিশোরগঞ্জ", lat: "24.444937", long: "90.776575" },
  { id: "7", division_id: "3", name: "Madaripur", bn_name: "মাদারীপুর", lat: "23.164102", long: "90.1896805" },
  { id: "8", division_id: "3", name: "Manikganj", bn_name: "মানিকগঞ্জ", lat: "23.8644", long: "90.0047" },
  { id: "9", division_id: "3", name: "Munshiganj", bn_name: "মুন্সিগঞ্জ", lat: "23.5422", long: "90.5305" },
  { id: "10", division_id: "8", name: "Mymensingh", bn_name: "ময়মনসিংহ", lat: "24.7471", long: "90.4203" },
  { id: "11", division_id: "3", name: "Narayanganj", bn_name: "নারায়াণগঞ্জ", lat: "23.63366", long: "90.496482" },
  { id: "12", division_id: "3", name: "Narsingdi", bn_name: "নরসিংদী", lat: "23.932233", long: "90.71541" },
  { id: "13", division_id: "8", name: "Netrokona", bn_name: "নেত্রকোণা", lat: "24.870955", long: "90.727887" },
  { id: "14", division_id: "3", name: "Rajbari", bn_name: "রাজবাড়ি", lat: "23.7574305", long: "89.6444665" },
  { id: "15", division_id: "3", name: "Shariatpur", bn_name: "শরীয়তপুর", lat: "23.2423", long: "90.4348" },
  { id: "16", division_id: "8", name: "Sherpur", bn_name: "শেরপুর", lat: "25.0204933", long: "90.0152966" },
  { id: "17", division_id: "8", name: "Tangail", bn_name: "টাঙ্গাইল", lat: "24.2513", long: "89.9167" },
  { id: "18", division_id: "5", name: "Bogura", bn_name: "বগুড়া", lat: "24.8465228", long: "89.377755" },
  { id: "19", division_id: "5", name: "Joypurhat", bn_name: "জয়পুরহাট", lat: "25.0968", long: "89.0227" },
  { id: "20", division_id: "5", name: "Naogaon", bn_name: "নওগাঁ", lat: "24.7936", long: "88.9318" },
  { id: "21", division_id: "5", name: "Natore", bn_name: "নাটোর", lat: "24.420556", long: "89.000282" },
  { id: "22", division_id: "5", name: "Nawabganj", bn_name: "নবাবগঞ্জ", lat: "24.5965034", long: "88.2775122" },
  { id: "23", division_id: "5", name: "Pabna", bn_name: "পাবনা", lat: "23.998524", long: "89.233645" },
  { id: "24", division_id: "5", name: "Rajshahi", bn_name: "রাজশাহী", lat: "24.3745", long: "88.6042" },
  { id: "25", division_id: "5", name: "Sirajgonj", bn_name: "সিরাজগঞ্জ", lat: "24.4533978", long: "89.7006815" },
  { id: "26", division_id: "6", name: "Dinajpur", bn_name: "দিনাজপুর", lat: "25.6217061", long: "88.6354504" },
  { id: "27", division_id: "6", name: "Gaibandha", bn_name: "গাইবান্ধা", lat: "25.328751", long: "89.528088" },
  { id: "28", division_id: "6", name: "Kurigram", bn_name: "কুড়িগ্রাম", lat: "25.805445", long: "89.636174" },
  { id: "29", division_id: "6", name: "Lalmonirhat", bn_name: "লালমনিরহাট", lat: "25.9923", long: "89.2847" },
  { id: "30", division_id: "6", name: "Nilphamari", bn_name: "নীলফামারী", lat: "25.931794", long: "88.856006" },
  { id: "31", division_id: "6", name: "Panchagarh", bn_name: "পঞ্চগড়", lat: "26.3411", long: "88.5541606" },
  { id: "32", division_id: "6", name: "Rangpur", bn_name: "রংপুর", lat: "25.7558096", long: "89.244462" },
  { id: "33", division_id: "6", name: "Thakurgaon", bn_name: "ঠাকুরগাঁও", lat: "26.0336945", long: "88.4616834" },
  { id: "34", division_id: "1", name: "Barguna", bn_name: "বরগুনা", lat: "22.0953", long: "90.1121" },
  { id: "35", division_id: "1", name: "Barishal", bn_name: "বরিশাল", lat: "22.7010", long: "90.3535" },
  { id: "36", division_id: "1", name: "Bhola", bn_name: "ভোলা", lat: "22.685923", long: "90.648179" },
  { id: "37", division_id: "1", name: "Jhalokati", bn_name: "ঝালকাঠি", lat: "22.6406", long: "90.1987" },
  { id: "38", division_id: "1", name: "Patuakhali", bn_name: "পটুয়াখালী", lat: "22.3596316", long: "90.3298712" },
  { id: "39", division_id: "1", name: "Pirojpur", bn_name: "পিরোজpour", lat: "22.5841", long: "89.9720" },
  { id: "40", division_id: "2", name: "Bandarban", bn_name: "বান্দরবন", lat: "22.1953275", long: "92.2183773" },
  { id: "41", division_id: "2", name: "Brahmanbaria", bn_name: "ব্রাহ্মণবাড়িয়া", lat: "23.9570904", long: "91.1119286" },
  { id: "42", division_id: "2", name: "Chandpur", bn_name: "চাঁদপুর", lat: "23.2332585", long: "90.6712912" },
  { id: "43", division_id: "2", name: "Chattogram", bn_name: "চট্টগ্রাম", lat: "22.335109", long: "91.834073" },
  { id: "44", division_id: "2", name: "Cumilla", bn_name: "কুমিল্লা", lat: "23.4682747", long: "91.1788135" },
  { id: "45", division_id: "2", name: "Cox's Bazar", bn_name: "কক্স বাজার", lat: "21.4272", long: "92.0058" },
  { id: "46", division_id: "2", name: "Feni", bn_name: "ফেনী", lat: "23.0159", long: "91.3976" },
  { id: "47", division_id: "2", name: "Khagrachari", bn_name: "খাগড়াছরি", lat: "23.119285", long: "91.984663" },
  { id: "48", division_id: "2", name: "Lakshmipur", bn_name: "লক্ষ্মীপুর", lat: "22.942477", long: "90.841184" },
  { id: "49", division_id: "2", name: "Noakhali", bn_name: "নোয়াখালী", lat: "22.869563", long: "91.099398" },
  { id: "50", division_id: "2", name: "Rangamati", bn_name: "রঙ্গামাটি", lat: "22.7324", long: "92.2985" },
  { id: "51", division_id: "7", name: "Habiganj", bn_name: "হবিগঞ্জ", lat: "24.374945", long: "91.41553" },
  { id: "52", division_id: "7", name: "Maulvibazar", bn_name: "মৌলভীবাজার", lat: "24.482934", long: "91.777417" },
  { id: "53", division_id: "7", name: "Sunamganj", bn_name: "সুনামগঞ্জ", lat: "25.0658042", long: "91.3950115" },
  { id: "54", division_id: "7", name: "Sylhet", bn_name: "সিলেট", lat: "24.8897956", long: "91.8697894" },
  { id: "55", division_id: "4", name: "Bagerhat", bn_name: "বাগেরহাট", lat: "22.651568", long: "89.785938" },
  { id: "56", division_id: "4", name: "Chuadanga", bn_name: "চুয়াডাঙ্গা", lat: "23.6401961", long: "88.841841" },
  { id: "57", division_id: "4", name: "Jashore", bn_name: "যশোর", lat: "23.16643", long: "89.2081126" },
  { id: "58", division_id: "4", name: "Jhenaidah", bn_name: "ঝিনাইদহ", lat: "23.5448176", long: "89.1539213" },
  { id: "59", division_id: "4", name: "Khulna", bn_name: "খুলনা", lat: "22.815774", long: "89.568679" },
  { id: "60", division_id: "4", name: "Kushtia", bn_name: "কুষ্টিয়া", lat: "23.901258", long: "89.120482" },
  { id: "61", division_id: "4", name: "Magura", bn_name: "মাগুরা", lat: "23.487337", long: "89.419956" },
  { id: "62", division_id: "4", name: "Meherpur", bn_name: "মেহেরপুর", lat: "23.762213", long: "88.631821" },
  { id: "63", division_id: "4", name: "Narail", bn_name: "নড়াইল", lat: "23.172534", long: "89.512672" },
  { id: "64", division_id: "4", name: "Satkhira", bn_name: "সাতক্ষীরা", lat: "22.7185", long: "89.0705" }
]

export const THANA_OPTIONS = [
  // Dhaka District (ID: 1)
  { id: "1", district_id: "1", name: "Dhamrai", bn_name: "ধামরাই" },
  { id: "2", district_id: "1", name: "Dohar", bn_name: "দোহার" },
  { id: "3", district_id: "1", name: "Keraniganj", bn_name: "কেরানীগঞ্জ" },
  { id: "4", district_id: "1", name: "Nawabganj", bn_name: "নবাবগঞ্জ" },
  { id: "5", district_id: "1", name: "Savar", bn_name: "সাভার" },

  // Faridpur (ID: 2)
  { id: "6", district_id: "2", name: "Alfadanga", bn_name: "আলফাডাঙ্গা" },
  { id: "7", district_id: "2", name: "Bhanga", bn_name: "ভাঙ্গা" },
  { id: "8", district_id: "2", name: "Boalmari", bn_name: "বোয়ালমারী" },
  { id: "9", district_id: "2", name: "Charbhadrasan", bn_name: "চরভদ্রাসন" },
  { id: "10", district_id: "2", name: "Faridpur Sadar", bn_name: "ফরিদপুর সদর" },
  { id: "11", district_id: "2", name: "Madhukhali", bn_name: "মধুখালী" },
  { id: "12", district_id: "2", name: "Nagarkanda", bn_name: "নগরকান্দা" },
  { id: "13", district_id: "2", name: "Sadarpur", bn_name: "সদরপুর" },
  { id: "14", district_id: "2", name: "Saltha", bn_name: "সালথা" },

  // Gazipur (ID: 3)
  { id: "15", district_id: "3", name: "Gazipur Sadar", bn_name: "গাজীপুর সদর" },
  { id: "16", district_id: "3", name: "Kaliakair", bn_name: "কালিয়াকৈর" },
  { id: "17", district_id: "3", name: "Kaliganj", bn_name: "কালীগঞ্জ" },
  { id: "18", district_id: "3", name: "Kapasia", bn_name: "কাপাসিয়া" },
  { id: "19", district_id: "3", name: "Sreepur", bn_name: "শ্রীপুর" },
  
  // Gopalganj (ID: 4)
  { id: "20", district_id: "4", name: "Gopalganj Sadar", bn_name: "গোপালগঞ্জ সদর" },
  { id: "21", district_id: "4", name: "Kashiani", bn_name: "কাশিয়ানী" },
  { id: "22", district_id: "4", name: "Kotalipara", bn_name: "কোটালীপাড়া" },
  { id: "23", district_id: "4", name: "Muksudpur", bn_name: "মুকসুদপুর" },
  { id: "24", district_id: "4", name: "Tungipara", bn_name: "টুঙ্গিপাড়া" },

  // Jamalpur (ID: 5)
  { id: "25", district_id: "5", name: "Baksiganj", bn_name: "বকশিগঞ্জ" },
  { id: "26", district_id: "5", name: "Dewanganj", bn_name: "দেওয়ানগঞ্জ" },
  { id: "27", district_id: "5", name: "Islampur", bn_name: "ইসলামপুর" },
  { id: "28", district_id: "5", name: "Jamalpur Sadar", bn_name: "জামালপুর সদর" },
  { id: "29", district_id: "5", name: "Madarganj", bn_name: "মাদারগঞ্জ" },
  { id: "30", district_id: "5", name: "Melandaha", bn_name: "মেলান্দহ" },
  { id: "31", district_id: "5", name: "Sarishabari", bn_name: "সরিষাবাড়ী" },

  // Kishoreganj (ID: 6)
  { id: "32", district_id: "6", name: "Austagram", bn_name: "অষ্টগ্রাম" },
  { id: "33", district_id: "6", name: "Bajitpur", bn_name: "বাজিতপুর" },
  { id: "34", district_id: "6", name: "Bhairab", bn_name: "ভৈরব" },
  { id: "35", district_id: "6", name: "Hossainpur", bn_name: "হোসেনপুর" },
  { id: "36", district_id: "6", name: "Itna", bn_name: "ইটনা" },
  { id: "37", district_id: "6", name: "Karimganj", bn_name: "করিমগঞ্জ" },
  { id: "38", district_id: "6", name: "Katiadi", bn_name: "কটিয়াদী" },
  { id: "39", district_id: "6", name: "Kishoreganj Sadar", bn_name: "কিশোরগঞ্জ সদর" },
  { id: "40", district_id: "6", name: "Kuliarchar", bn_name: "কুলিয়ারচর" },
  { id: "41", district_id: "6", name: "Mithamain", bn_name: "মিঠামইন" },
  { id: "42", district_id: "6", name: "Nikli", bn_name: "নিকলী" },
  { id: "43", district_id: "6", name: "Pakundia", bn_name: "পাকুন্দিয়া" },
  { id: "44", district_id: "6", name: "Tarail", bn_name: "তাড়াইল" },

  // Madaripur (ID: 7)
  { id: "45", district_id: "7", name: "Dasar", bn_name: "ডাসার" },
  { id: "46", district_id: "7", name: "Kalkini", bn_name: "কালকিনি" },
  { id: "47", district_id: "7", name: "Madaripur Sadar", bn_name: "মাদারীপুর সদর" },
  { id: "48", district_id: "7", name: "Rajoir", bn_name: "রাজৈর" },
  { id: "49", district_id: "7", name: "Shibchar", bn_name: "শিবচর" },

  // Manikganj (ID: 8)
  { id: "50", district_id: "8", name: "Daulatpur", bn_name: "দৌলতপুর" },
  { id: "51", district_id: "8", name: "Ghior", bn_name: "ঘিওর" },
  { id: "52", district_id: "8", name: "Harirampur", bn_name: "হরিরামপুর" },
  { id: "53", district_id: "8", name: "Manikganj Sadar", bn_name: "মানিকগঞ্জ সদর" },
  { id: "54", district_id: "8", name: "Saturia", bn_name: "সাটুরিয়া" },
  { id: "55", district_id: "8", name: "Shivalaya", bn_name: "শিবালয়" },
  { id: "56", district_id: "8", name: "Singair", bn_name: "সিঙ্গাইর" },

  // Munshiganj (ID: 9)
  { id: "57", district_id: "9", name: "Gazaria", bn_name: "গজারিয়া" },
  { id: "58", district_id: "9", name: "Lauhajang", bn_name: "লৌহজং" },
  { id: "59", district_id: "9", name: "Munshiganj Sadar", bn_name: "মুন্সিগঞ্জ সদর" },
  { id: "60", district_id: "9", name: "Sirajdikhan", bn_name: "সিরাজদীখান" },
  { id: "61", district_id: "9", name: "Sreenagar", bn_name: "শ্রীনগর" },
  { id: "62", district_id: "9", name: "Tongibari", bn_name: "টংগিবাড়ী" },

  // Mymensingh (ID: 10)
  { id: "63", district_id: "10", name: "Bhaluka", bn_name: "ভালুকা" },
  { id: "64", district_id: "10", name: "Dhobaura", bn_name: "ধোবাউড়া" },
  { id: "65", district_id: "10", name: "Fulbaria", bn_name: "ফুলবাড়ীয়া" },
  { id: "66", district_id: "10", name: "Gaffargaon", bn_name: "গফরগাঁও" },
  { id: "67", district_id: "10", name: "Gauripur", bn_name: "গৌরীপুর" },
  { id: "68", district_id: "10", name: "Haluaghat", bn_name: "হালুয়াঘাট" },
  { id: "69", district_id: "10", name: "Ishwarganj", bn_name: "ঈশ্বরগঞ্জ" },
  { id: "70", district_id: "10", name: "Muktagacha", bn_name: "মুক্তাগাছা" },
  { id: "71", district_id: "10", name: "Mymensingh Sadar", bn_name: "ময়মনসিংহ সদর" },
  { id: "72", district_id: "10", name: "Nandail", bn_name: "নান্দাইল" },
  { id: "73", district_id: "10", name: "Phulpur", bn_name: "ফুলপুর" },
  { id: "74", district_id: "10", name: "Tarakanda", bn_name: "তারাকান্দা" },
  { id: "75", district_id: "10", name: "Trishal", bn_name: "ত্রিশাল" },

  // Narayanganj (ID: 11)
  { id: "76", district_id: "11", name: "Araihazar", bn_name: "আড়াইহাজার" },
  { id: "77", district_id: "11", name: "Bandar", bn_name: "বন্দর" },
  { id: "78", district_id: "11", name: "Narayanganj Sadar", bn_name: "নারায়ণগঞ্জ সদর" },
  { id: "79", district_id: "11", name: "Rupganj", bn_name: "রূপগঞ্জ" },
  { id: "80", district_id: "11", name: "Sonargaon", bn_name: "সোনারগাঁ" },

  // Narsingdi (ID: 12)
  { id: "81", district_id: "12", name: "Belabo", bn_name: "বেলাবো" },
  { id: "82", district_id: "12", name: "Monohardi", bn_name: "মনোহরদী" },
  { id: "83", district_id: "12", name: "Narsingdi Sadar", bn_name: "নরসিংদী সদর" },
  { id: "84", district_id: "12", name: "Palash", bn_name: "পলাশ" },
  { id: "85", district_id: "12", name: "Raipura", bn_name: "রায়পুরা" },
  { id: "86", district_id: "12", name: "Shibpur", bn_name: "শিবপুর" },

  // Netrokona (ID: 13)
  { id: "87", district_id: "13", name: "Atpara", bn_name: "আটপাড়া" },
  { id: "88", district_id: "13", name: "Barhatta", bn_name: "বরহাট্টা" },
  { id: "89", district_id: "13", name: "Durgapur", bn_name: "দুর্গাপুর" },
  { id: "90", district_id: "13", name: "Kalmakanda", bn_name: "কলমাকান্দা" },
  { id: "91", district_id: "13", name: "Kendua", bn_name: "কেন্দুয়া" },
  { id: "92", district_id: "13", name: "Khaliajuri", bn_name: "খালিয়াজুরী" },
  { id: "93", district_id: "13", name: "Madan", bn_name: "মদন" },
  { id: "94", district_id: "13", name: "Mohanganj", bn_name: "মোহনগঞ্জ" },
  { id: "95", district_id: "13", name: "Netrokona Sadar", bn_name: "নেত্রকোণা সদর" },
  { id: "96", district_id: "13", name: "Purbadhala", bn_name: "পূর্বধলা" },

  // Rajbari (ID: 14)
  { id: "97", district_id: "14", name: "Baliakandi", bn_name: "বালিয়াকান্দি" },
  { id: "98", district_id: "14", name: "Goalandaghat", bn_name: "গোয়ালন্দ ঘাট" },
  { id: "99", district_id: "14", name: "Kalukhali", bn_name: "কালুখালী" },
  { id: "100", district_id: "14", name: "Pangsha", bn_name: "পাংশা" },
  { id: "101", district_id: "14", name: "Rajbari Sadar", bn_name: "রাজবাড়ী সদর" },

  // Shariatpur (ID: 15)
  { id: "102", district_id: "15", name: "Bhedarganj", bn_name: "ভেদরগঞ্জ" },
  { id: "103", district_id: "15", name: "Damudya", bn_name: "ডামুড্যা" },
  { id: "104", district_id: "15", name: "Gosairhat", bn_name: "গোসাইরহাট" },
  { id: "105", district_id: "15", name: "Naria", bn_name: "নড়িয়া" },
  { id: "106", district_id: "15", name: "Shariatpur Sadar", bn_name: "শরীয়তপুর সদর" },
  { id: "107", district_id: "15", name: "Zajira", bn_name: "জাজিরা" },

  // Sherpur (ID: 16)
  { id: "108", district_id: "16", name: "Jhenaigati", bn_name: "ঝিনাইগাতী" },
  { id: "109", district_id: "16", name: "Nakla", bn_name: "নকলা" },
  { id: "110", district_id: "16", name: "Nalitabari", bn_name: "নালিতাবাড়ী" },
  { id: "111", district_id: "16", name: "Sherpur Sadar", bn_name: "শেরপুর সদর" },
  { id: "112", district_id: "16", name: "Sreebardi", bn_name: "শ্রীবরদী" },

  // Tangail (ID: 17)
  { id: "113", district_id: "17", name: "Basail", bn_name: "বাসাইল" },
  { id: "114", district_id: "17", name: "Bhuapur", bn_name: "ভূঞাপুর" },
  { id: "115", district_id: "17", name: "Delduar", bn_name: "দেলদুয়ার" },
  { id: "116", district_id: "17", name: "Dhanbari", bn_name: "ধনবাড়ী" },
  { id: "117", district_id: "17", name: "Ghatail", bn_name: "ঘাটাইল" },
  { id: "118", district_id: "17", name: "Gopalpur", bn_name: "গোপালপুর" },
  { id: "119", district_id: "17", name: "Kalihati", bn_name: "কালিহাতী" },
  { id: "120", district_id: "17", name: "Madhupur", bn_name: "মধুপুর" },
  { id: "121", district_id: "17", name: "Mirzapur", bn_name: "মির্জাপুর" },
  { id: "122", district_id: "17", name: "Nagarpur", bn_name: "নাগরপুর" },
  { id: "123", district_id: "17", name: "Sakhipur", bn_name: "সখিপুর" },
  { id: "124", district_id: "17", name: "Tangail Sadar", bn_name: "টাঙ্গাইল সদর" },

  // Bogura (ID: 18)
  { id: "125", district_id: "18", name: "Adamdighi", bn_name: "আদমদীঘি" },
  { id: "126", district_id: "18", name: "Bogura Sadar", bn_name: "বগুড়া সদর" },
  { id: "127", district_id: "18", name: "Dhunat", bn_name: "ধুনট" },
  { id: "128", district_id: "18", name: "Dhupchanchia", bn_name: "দুপচাঁচিয়া" },
  { id: "129", district_id: "18", name: "Gabtali", bn_name: "গাবতলী" },
  { id: "130", district_id: "18", name: "Kahaloo", bn_name: "কাহালু" },
  { id: "131", district_id: "18", name: "Nandigram", bn_name: "নন্দিগ্রাম" },
  { id: "132", district_id: "18", name: "Sariakandi", bn_name: "সারিয়াকান্দি" },
  { id: "133", district_id: "18", name: "Shajahanpur", bn_name: "শাজাহানপুর" },
  { id: "134", district_id: "18", name: "Sherpur", bn_name: "শেরপুর" },
  { id: "135", district_id: "18", name: "Shibganj", bn_name: "শিবগঞ্জ" },
  { id: "136", district_id: "18", name: "Sonatala", bn_name: "সোনাতলা" },

  // Joypurhat (ID: 19)
  { id: "137", district_id: "19", name: "Akkelpur", bn_name: "আক্কেলপুর" },
  { id: "138", district_id: "19", name: "Joypurhat Sadar", bn_name: "জয়পুরহাট সদর" },
  { id: "139", district_id: "19", name: "Kalai", bn_name: "কালাই" },
  { id: "140", district_id: "19", name: "Khetlal", bn_name: "ক্ষেতলাল" },
  { id: "141", district_id: "19", name: "Panchbibi", bn_name: "পাঁচবিবি" },

  // Naogaon (ID: 20)
  { id: "142", district_id: "20", name: "Atrai", bn_name: "আত্রাই" },
  { id: "143", district_id: "20", name: "Badalgachhi", bn_name: "বদলগাছী" },
  { id: "144", district_id: "20", name: "Dhamoirhat", bn_name: "ধামইরহাট" },
  { id: "145", district_id: "20", name: "Manda", bn_name: "মান্দা" },
  { id: "146", district_id: "20", name: "Mohadevpur", bn_name: "মহাদেবপুর" },
  { id: "147", district_id: "20", name: "Naogaon Sadar", bn_name: "নওগাঁ সদর" },
  { id: "148", district_id: "20", name: "Niamatpur", bn_name: "নিয়ামতপুর" },
  { id: "149", district_id: "20", name: "Patnitala", bn_name: "পত্নীতলা" },
  { id: "150", district_id: "20", name: "Porsha", bn_name: "পোরশা" },
  { id: "151", district_id: "20", name: "Raninagar", bn_name: "রাণীনগর" },
  { id: "152", district_id: "20", name: "Sapahar", bn_name: "সাপাহার" },

  // Natore (ID: 21)
  { id: "153", district_id: "21", name: "Bagatipara", bn_name: "বাগাতিপাড়া" },
  { id: "154", district_id: "21", name: "Baraigram", bn_name: "বড়াইগ্রাম" },
  { id: "155", district_id: "21", name: "Gurudaspur", bn_name: "গুরুদাসপুর" },
  { id: "156", district_id: "21", name: "Lalpur", bn_name: "লালপুর" },
  { id: "157", district_id: "21", name: "Naldanga", bn_name: "নলডাঙ্গা" },
  { id: "158", district_id: "21", name: "Natore Sadar", bn_name: "নাটোর সদর" },
  { id: "159", district_id: "21", name: "Singra", bn_name: "সিংড়া" },

  // Chapai Nawabganj (ID: 22)
  { id: "160", district_id: "22", name: "Bholahat", bn_name: "ভোলাহাট" },
  { id: "161", district_id: "22", name: "Chapai Nawabganj Sadar", bn_name: "চাঁপাইনবাবগঞ্জ সদর" },
  { id: "162", district_id: "22", name: "Gomastapur", bn_name: "গোমস্তাপুর" },
  { id: "163", district_id: "22", name: "Nachole", bn_name: "নাচোল" },
  { id: "164", district_id: "22", name: "Shibganj", bn_name: "শিবগঞ্জ" },

  // Pabna (ID: 23)
  { id: "165", district_id: "23", name: "Atgharia", bn_name: "আটঘরিয়া" },
  { id: "166", district_id: "23", name: "Bera", bn_name: "বেড়া" },
  { id: "167", district_id: "23", name: "Bhangura", bn_name: "ভাঙ্গুড়া" },
  { id: "168", district_id: "23", name: "Chatmohar", bn_name: "চাটমোহর" },
  { id: "169", district_id: "23", name: "Faridpur", bn_name: "ফরিদপুর" },
  { id: "170", district_id: "23", name: "Ishwardi", bn_name: "ঈশ্বরদী" },
  { id: "171", district_id: "23", name: "Pabna Sadar", bn_name: "পাবনা সদর" },
  { id: "172", district_id: "23", name: "Santhia", bn_name: "সাঁথিয়া" },
  { id: "173", district_id: "23", name: "Sujanagar", bn_name: "সুজানগর" },

  // Rajshahi (ID: 24)
  { id: "174", district_id: "24", name: "Bagha", bn_name: "বাঘা" },
  { id: "175", district_id: "24", name: "Bagmara", bn_name: "বাগমারা" },
  { id: "176", district_id: "24", name: "Charghat", bn_name: "চারঘাট" },
  { id: "177", district_id: "24", name: "Durgapur", bn_name: "দুর্গাপুর" },
  { id: "178", district_id: "24", name: "Godagari", bn_name: "গোদাগাড়ী" },
  { id: "179", district_id: "24", name: "Mohanpur", bn_name: "মোহনপুর" },
  { id: "180", district_id: "24", name: "Paba", bn_name: "পবা" },
  { id: "181", district_id: "24", name: "Puthia", bn_name: "পুঠিয়া" },
  { id: "182", district_id: "24", name: "Tanore", bn_name: "তানোর" },

  // Sirajganj (ID: 25)
  { id: "183", district_id: "25", name: "Belkuchi", bn_name: "বেলকুচি" },
  { id: "184", district_id: "25", name: "Chauhali", bn_name: "চৌহালি" },
  { id: "185", district_id: "25", name: "Kamarkhanda", bn_name: "কামারখন্দ" },
  { id: "186", district_id: "25", name: "Kazipur", bn_name: "কাজীপুর" },
  { id: "187", district_id: "25", name: "Raiganj", bn_name: "রায়গঞ্জ" },
  { id: "188", district_id: "25", name: "Shahjadpur", bn_name: "শাহজাদপুর" },
  { id: "189", district_id: "25", name: "Sirajganj Sadar", bn_name: "সিরাজগঞ্জ সদর" },
  { id: "190", district_id: "25", name: "Tarash", bn_name: "তাড়াশ" },
  { id: "191", district_id: "25", name: "Ullahpara", bn_name: "উল্লাপাড়া" },

  // Dinajpur (ID: 26)
  { id: "192", district_id: "26", name: "Biral", bn_name: "বিরল" },
  { id: "193", district_id: "26", name: "Birampur", bn_name: "বিরামপুর" },
  { id: "194", district_id: "26", name: "Birganj", bn_name: "বীরগঞ্জ" },
  { id: "195", district_id: "26", name: "Bochaganj", bn_name: "বোচাগঞ্জ" },
  { id: "196", district_id: "26", name: "Chirirbandar", bn_name: "চিরিরবন্দর" },
  { id: "197", district_id: "26", name: "Dinajpur Sadar", bn_name: "দিনাজপুর সদর" },
  { id: "198", district_id: "26", name: "Ghoraghat", bn_name: "ঘোড়াঘাট" },
  { id: "199", district_id: "26", name: "Hakimpur", bn_name: "হাকিমপুর" },
  { id: "200", district_id: "26", name: "Kaharole", bn_name: "কাহারোল" },
  { id: "201", district_id: "26", name: "Khansama", bn_name: "খানসামা" },
  { id: "202", district_id: "26", name: "Nawabganj", bn_name: "নবাবগঞ্জ" },
  { id: "203", district_id: "26", name: "Parbatipur", bn_name: "পার্বতীপুর" },
  { id: "204", district_id: "26", name: "Phulbari", bn_name: "ফুলবাড়ী" },

  // Gaibandha (ID: 27)
  { id: "205", district_id: "27", name: "Fulchhari", bn_name: "ফুলছড়ি" },
  { id: "206", district_id: "27", name: "Gaibandha Sadar", bn_name: "গাইবান্ধা সদর" },
  { id: "207", district_id: "27", name: "Gobindaganj", bn_name: "গোবিন্দগঞ্জ" },
  { id: "208", district_id: "27", name: "Palashbari", bn_name: "পলাশবাড়ী" },
  { id: "209", district_id: "27", name: "Sadullapur", bn_name: "সাদুল্লাপুর" },
  { id: "210", district_id: "27", name: "Saghata", bn_name: "সাঘাটা" },
  { id: "211", district_id: "27", name: "Sundarganj", bn_name: "সুন্দরগঞ্জ" },

  // Kurigram (ID: 28)
  { id: "212", district_id: "28", name: "Bhurungamari", bn_name: "ভুরুঙ্গামারী" },
  { id: "213", district_id: "28", name: "Char Rajibpur", bn_name: "চর রাজিবপুর" },
  { id: "214", district_id: "28", name: "Chilmari", bn_name: "চিলমারী" },
  { id: "215", district_id: "28", name: "Kurigram Sadar", bn_name: "কুড়িগ্রাম সদর" },
  { id: "216", district_id: "28", name: "Nageshwari", bn_name: "নাগেশ্বরী" },
  { id: "217", district_id: "28", name: "Phulbari", bn_name: "ফুলবাড়ী" },
  { id: "218", district_id: "28", name: "Rajarhat", bn_name: "রাজারহাট" },
  { id: "219", district_id: "28", name: "Raomari", bn_name: "রৌমারী" },
  { id: "220", district_id: "28", name: "Ulipur", bn_name: "উলিপুর" },

  // Lalmonirhat (ID: 29)
  { id: "221", district_id: "29", name: "Aditmari", bn_name: "আদিতমারী" },
  { id: "222", district_id: "29", name: "Hatibandha", bn_name: "হাতীবান্ধা" },
  { id: "223", district_id: "29", name: "Kaliganj", bn_name: "কালীগঞ্জ" },
  { id: "224", district_id: "29", name: "Lalmonirhat Sadar", bn_name: "লালমনিরহাট সদর" },
  { id: "225", district_id: "29", name: "Patgram", bn_name: "পাটগ্রাম" },

  // Nilphamari (ID: 30)
  { id: "226", district_id: "30", name: "Dimla", bn_name: "ডিমলা" },
  { id: "227", district_id: "30", name: "Domar", bn_name: "ডোমার" },
  { id: "228", district_id: "30", name: "Jaldhaka", bn_name: "জলঢাকা" },
  { id: "229", district_id: "30", name: "Kishoreganj", bn_name: "কিশোরগঞ্জ" },
  { id: "230", district_id: "30", name: "Nilphamari Sadar", bn_name: "নীলফামারী সদর" },
  { id: "231", district_id: "30", name: "Saidpur", bn_name: "সৈয়দপুর" },

  // Panchagarh (ID: 31)
  { id: "232", district_id: "31", name: "Atwari", bn_name: "আটোয়ারী" },
  { id: "233", district_id: "31", name: "Boda", bn_name: "বোদা" },
  { id: "234", district_id: "31", name: "Debiganj", bn_name: "দেবীগঞ্জ" },
  { id: "235", district_id: "31", name: "Panchagarh Sadar", bn_name: "পঞ্চগড় সদর" },
  { id: "236", district_id: "31", name: "Tetulia", bn_name: "তেতুলিয়া" },

  // Rangpur (ID: 32)
  { id: "237", district_id: "32", name: "Badarganj", bn_name: "বদরগঞ্জ" },
  { id: "238", district_id: "32", name: "Gangachara", bn_name: "গংগাচড়া" },
  { id: "239", district_id: "32", name: "Kaunia", bn_name: "কাউনিয়া" },
  { id: "240", district_id: "32", name: "Mithapukur", bn_name: "মিঠাপুকুর" },
  { id: "241", district_id: "32", name: "Pirgachha", bn_name: "পীরগাছা" },
  { id: "242", district_id: "32", name: "Pirganj", bn_name: "পীরগঞ্জ" },
  { id: "243", district_id: "32", name: "Rangpur Sadar", bn_name: "রংপুর সদর" },
  { id: "244", district_id: "32", name: "Taraganj", bn_name: "তারাগঞ্জ" },

  // Thakurgaon (ID: 33)
  { id: "245", district_id: "33", name: "Baliadangi", bn_name: "বালিয়াডাঙ্গী" },
  { id: "246", district_id: "33", name: "Haripur", bn_name: "হরিপুর" },
  { id: "247", district_id: "33", name: "Pirganj", bn_name: "পীরগঞ্জ" },
  { id: "248", district_id: "33", name: "Ranisankail", bn_name: "রাণীশংকৈল" },
  { id: "249", district_id: "33", name: "Thakurgaon Sadar", bn_name: "ঠাকুরগাঁও সদর" },

  // Barguna (ID: 34)
  { id: "250", district_id: "34", name: "Amtali", bn_name: "আমতলী" },
  { id: "251", district_id: "34", name: "Bamna", bn_name: "বামনা" },
  { id: "252", district_id: "34", name: "Barguna Sadar", bn_name: "বরগুনা সদর" },
  { id: "253", district_id: "34", name: "Betagi", bn_name: "বেতাগি" },
  { id: "254", district_id: "34", name: "Patharghata", bn_name: "পাথরঘাটা" },
  { id: "255", district_id: "34", name: "Taltali", bn_name: "তালতলী" },

  // Barishal (ID: 35)
  { id: "256", district_id: "35", name: "Agailjhara", bn_name: "আগৈলঝাড়া" },
  { id: "257", district_id: "35", name: "Babuganj", bn_name: "বাবুগঞ্জ" },
  { id: "258", district_id: "35", name: "Bakerganj", bn_name: "বাকেরগঞ্জ" },
  { id: "259", district_id: "35", name: "Banaripara", bn_name: "বানারীপাড়া" },
  { id: "260", district_id: "35", name: "Barishal Sadar", bn_name: "বরিশাল সদর" },
  { id: "261", district_id: "35", name: "Gournadi", bn_name: "গৌরনদী" },
  { id: "262", district_id: "35", name: "Hizla", bn_name: "হিজলা" },
  { id: "263", district_id: "35", name: "Mehendiganj", bn_name: "মেহেন্দীগঞ্জ" },
  { id: "264", district_id: "35", name: "Muladi", bn_name: "মুলাদী" },
  { id: "265", district_id: "35", name: "Wazirpur", bn_name: "উজিরপুর" },

  // Bhola (ID: 36)
  { id: "266", district_id: "36", name: "Bhola Sadar", bn_name: "ভোলা সদর" },
  { id: "267", district_id: "36", name: "Borhanuddin", bn_name: "বোরহানউদ্দিন" },
  { id: "268", district_id: "36", name: "Char Fasson", bn_name: "চরফ্যাশন" },
  { id: "269", district_id: "36", name: "Daulatkhan", bn_name: "দৌলতখান" },
  { id: "270", district_id: "36", name: "Lalmohan", bn_name: "লালমোহন" },
  { id: "271", district_id: "36", name: "Manpura", bn_name: "মনপুরা" },
  { id: "272", district_id: "36", name: "Tazumuddin", bn_name: "তজুমদ্দিন" },

  // Jhalokati (ID: 37)
  { id: "273", district_id: "37", name: "Jhalokati Sadar", bn_name: "ঝালকাঠি সদর" },
  { id: "274", district_id: "37", name: "Kathalia", bn_name: "কাঁঠালিয়া" },
  { id: "275", district_id: "37", name: "Nalchity", bn_name: "নলছিটি" },
  { id: "276", district_id: "37", name: "Rajapur", bn_name: "রাজাপুর" },

  // Patuakhali (ID: 38)
  { id: "277", district_id: "38", name: "Bauphal", bn_name: "বাউফল" },
  { id: "278", district_id: "38", name: "Dashmina", bn_name: "দশমিনা" },
  { id: "279", district_id: "38", name: "Dumki", bn_name: "দুমকি" },
  { id: "280", district_id: "38", name: "Galachipa", bn_name: "গলাচিপা" },
  { id: "281", district_id: "38", name: "Kalapara", bn_name: "কলাপাড়া" },
  { id: "282", district_id: "38", name: "Mirzaganj", bn_name: "মির্জাগঞ্জ" },
  { id: "283", district_id: "38", name: "Patuakhali Sadar", bn_name: "পটুয়াখালী সদর" },
  { id: "284", district_id: "38", name: "Rangabali", bn_name: "রাঙ্গাবালী" },

  // Pirojpur (ID: 39)
  { id: "285", district_id: "39", name: "Bhandaria", bn_name: "ভান্ডারিয়া" },
  { id: "286", district_id: "39", name: "Indurkani", bn_name: "ইন্দুরকানী" },
  { id: "287", district_id: "39", name: "Kawkhali", bn_name: "কাউখালী" },
  { id: "288", district_id: "39", name: "Mathbaria", bn_name: "মঠবাড়ীয়া" },
  { id: "289", district_id: "39", name: "Nazirpur", bn_name: "নাজিরপুর" },
  { id: "290", district_id: "39", name: "Nesarabad (Swarupkati)", bn_name: "নেছারাবাদ" },
  { id: "291", district_id: "39", name: "Pirojpur Sadar", bn_name: "পিরোজপুর সদর" },

  // Bandarban (ID: 40)
  { id: "292", district_id: "40", name: "Alikadam", bn_name: "আলীকদম" },
  { id: "293", district_id: "40", name: "Bandarban Sadar", bn_name: "বান্দরবান সদর" },
  { id: "294", district_id: "40", name: "Lama", bn_name: "লামা" },
  { id: "295", district_id: "40", name: "Naikhongchhari", bn_name: "নাইক্ষ্যংছড়ি" },
  { id: "296", district_id: "40", name: "Rowangchhari", bn_name: "রোয়াংছড়ি" },
  { id: "297", district_id: "40", name: "Ruma", bn_name: "রুমা" },
  { id: "298", district_id: "40", name: "Thanchi", bn_name: "থানচি" },

  // Brahmanbaria (ID: 41)
  { id: "299", district_id: "41", name: "Akhaura", bn_name: "আখাউড়া" },
  { id: "300", district_id: "41", name: "Ashuganj", bn_name: "আশুগঞ্জ" },
  { id: "301", district_id: "41", name: "Bancharampur", bn_name: "বাঞ্ছারামপুর" },
  { id: "302", district_id: "41", name: "Brahmanbaria Sadar", bn_name: "ব্রাহ্মণবাড়িয়া সদর" },
  { id: "303", district_id: "41", name: "Bijoynagar", bn_name: "বিজয়নগর" },
  { id: "304", district_id: "41", name: "Kasba", bn_name: "কসবা" },
  { id: "305", district_id: "41", name: "Nabinagar", bn_name: "নবীনগর" },
  { id: "306", district_id: "41", name: "Nasirnagar", bn_name: "নাসিরনগর" },
  { id: "307", district_id: "41", name: "Sarail", bn_name: "সরাইল" },

  // Chandpur (ID: 42)
  { id: "308", district_id: "42", name: "Chandpur Sadar", bn_name: "চাঁদপুর সদর" },
  { id: "309", district_id: "42", name: "Faridganj", bn_name: "ফরিদগঞ্জ" },
  { id: "310", district_id: "42", name: "Haimchar", bn_name: "হাইমচর" },
  { id: "311", district_id: "42", name: "Hajiganj", bn_name: "হাজীগঞ্জ" },
  { id: "312", district_id: "42", name: "Kachua", bn_name: "কচুয়া" },
  { id: "313", district_id: "42", name: "Matlab North", bn_name: "মতলব উত্তর" },
  { id: "314", district_id: "42", name: "Matlab South", bn_name: "মতলব দক্ষিণ" },
  { id: "315", district_id: "42", name: "Shahrasti", bn_name: "শাহরাস্তি" },

  // Chattogram (ID: 43)
  { id: "316", district_id: "43", name: "Anwara", bn_name: "আনোয়ারা" },
  { id: "317", district_id: "43", name: "Banshkhali", bn_name: "বাঁশখালী" },
  { id: "318", district_id: "43", name: "Boalkhali", bn_name: "বোয়ালখালী" },
  { id: "319", district_id: "43", name: "Chandanaish", bn_name: "চন্দনাইশ" },
  { id: "320", district_id: "43", name: "Fatikchhari", bn_name: "ফটিকছড়ি" },
  { id: "321", district_id: "43", name: "Hathazari", bn_name: "হাটহাজারী" },
  { id: "322", district_id: "43", name: "Karnaphuli", bn_name: "কর্ণফুলী" },
  { id: "323", district_id: "43", name: "Lohagara", bn_name: "লোহাগাড়া" },
  { id: "324", district_id: "43", name: "Mirsharai", bn_name: "মীরসরাই" },
  { id: "325", district_id: "43", name: "Patiya", bn_name: "পটিয়া" },
  { id: "326", district_id: "43", name: "Rangunia", bn_name: "রাঙ্গুনিয়া" },
  { id: "327", district_id: "43", name: "Raozan", bn_name: "রাউজান" },
  { id: "328", district_id: "43", name: "Sandwip", bn_name: "সন্দ্বীপ" },
  { id: "329", district_id: "43", name: "Satkania", bn_name: "সাতকানিয়া" },
  { id: "330", district_id: "43", name: "Sitakunda", bn_name: "সীতাকুণ্ড" },

  // Cumilla (ID: 44)
  { id: "331", district_id: "44", name: "Barura", bn_name: "বরুড়া" },
  { id: "332", district_id: "44", name: "Brahmanpara", bn_name: "ব্রাহ্মণপাড়া" },
  { id: "333", district_id: "44", name: "Burichang", bn_name: "বুড়িচং" },
  { id: "334", district_id: "44", name: "Chandina", bn_name: "চান্দিনা" },
  { id: "335", district_id: "44", name: "Chauddagram", bn_name: "চৌদ্দগ্রাম" },
  { id: "336", district_id: "44", name: "Cumilla Adarsha Sadar", bn_name: "কুমিল্লা আদর্শ সদর" },
  { id: "337", district_id: "44", name: "Cumilla Sadar South", bn_name: "কুমিল্লা সদর দক্ষিণ" },
  { id: "338", district_id: "44", name: "Daudkandi", bn_name: "দাউদকান্দি" },
  { id: "339", district_id: "44", name: "Debidwar", bn_name: "দেবীদ্বার" },
  { id: "340", district_id: "44", name: "Homna", bn_name: "হোমনা" },
  { id: "341", district_id: "44", name: "Laksam", bn_name: "লাকসাম" },
  { id: "342", district_id: "44", name: "Lalmai", bn_name: "লালমাই" },
  { id: "343", district_id: "44", name: "Meghna", bn_name: "মেঘনা" },
  { id: "344", district_id: "44", name: "Monoharganj", bn_name: "মনোহরগঞ্জ" },
  { id: "345", district_id: "44", name: "Muradnagar", bn_name: "মুরাদনগর" },
  { id: "346", district_id: "44", name: "Nangalkot", bn_name: "নাঙ্গলকোট" },
  { id: "347", district_id: "44", name: "Titas", bn_name: "তিতাস" },

  // Cox's Bazar (ID: 45)
  { id: "348", district_id: "45", name: "Chakaria", bn_name: "চকোরিয়া" },
  { id: "349", district_id: "45", name: "Cox's Bazar Sadar", bn_name: "কক্সবাজার সদর" },
  { id: "350", district_id: "45", name: "Eidgaon", bn_name: "ঈদগাঁও" },
  { id: "351", district_id: "45", name: "Kutubdia", bn_name: "কুতুবদিয়া" },
  { id: "352", district_id: "45", name: "Moheshkhali", bn_name: "মহেশখালী" },
  { id: "353", district_id: "45", name: "Pekua", bn_name: "পেকুয়া" },
  { id: "354", district_id: "45", name: "Ramu", bn_name: "রামু" },
  { id: "355", district_id: "45", name: "Teknaf", bn_name: "টেকনাফ" },
  { id: "356", district_id: "45", name: "Ukhia", bn_name: "উখিয়া" },

  // Feni (ID: 46)
  { id: "357", district_id: "46", name: "Chhagalnaiya", bn_name: "ছাগলনাইয়া" },
  { id: "358", district_id: "46", name: "Daganbhuiyan", bn_name: "দাগনভূঞা" },
  { id: "359", district_id: "46", name: "Feni Sadar", bn_name: "ফেনী সদর" },
  { id: "360", district_id: "46", name: "Fulgazi", bn_name: "ফুলগাজী" },
  { id: "361", district_id: "46", name: "Parshuram", bn_name: "পরশুরাম" },
  { id: "362", district_id: "46", name: "Sonagazi", bn_name: "সোনাগাজী" },

  // Khagrachari (ID: 47)
  { id: "363", district_id: "47", name: "Dighinala", bn_name: "দীঘিনালা" },
  { id: "364", district_id: "47", name: "Guimara", bn_name: "গুইমারা" },
  { id: "365", district_id: "47", name: "Khagrachari Sadar", bn_name: "খাগড়াছড়ি সদর" },
  { id: "366", district_id: "47", name: "Lakshmichhari", bn_name: "লক্ষ্মীছড়ি" },
  { id: "367", district_id: "47", name: "Mahalchhari", bn_name: "মহালছড়ি" },
  { id: "368", district_id: "47", name: "Manikchhari", bn_name: "মানিকছড়ি" },
  { id: "369", district_id: "47", name: "Matiranga", bn_name: "মাটিরাঙ্গা" },
  { id: "370", district_id: "47", name: "Panchhari", bn_name: "পানছড়ি" },
  { id: "371", district_id: "47", name: "Ramgarh", bn_name: "রামগড়" },

  // Lakshmipur (ID: 48)
  { id: "372", district_id: "48", name: "Kamalnagar", bn_name: "কমলনগর" },
  { id: "373", district_id: "48", name: "Lakshmipur Sadar", bn_name: "লক্ষ্মীপুর সদর" },
  { id: "374", district_id: "48", name: "Raipur", bn_name: "রায়পুর" },
  { id: "375", district_id: "48", name: "Ramganj", bn_name: "রামগঞ্জ" },
  { id: "376", district_id: "48", name: "Ramgati", bn_name: "রামগতি" },

  // Noakhali (ID: 49)
  { id: "377", district_id: "49", name: "Begumganj", bn_name: "বেগমগঞ্জ" },
  { id: "378", district_id: "49", name: "Chatkhil", bn_name: "চাটখিল" },
  { id: "379", district_id: "49", name: "Companiganj", bn_name: "কোম্পানীগঞ্জ" },
  { id: "380", district_id: "49", name: "Hatiya", bn_name: "হাতিয়া" },
  { id: "381", district_id: "49", name: "Kabirhat", bn_name: "কবিরহাট" },
  { id: "382", district_id: "49", name: "Noakhali Sadar", bn_name: "নোয়াখালী সদর" },
  { id: "383", district_id: "49", name: "Senbagh", bn_name: "সেনবাগ" },
  { id: "384", district_id: "49", name: "Sonaimuri", bn_name: "সোনাইমুড়ী" },
  { id: "385", district_id: "49", name: "Subarnachar", bn_name: "সুবর্ণচর" },

  // Rangamati (ID: 50)
  { id: "386", district_id: "50", name: "Bagaichhari", bn_name: "বাঘাইছড়ি" },
  { id: "387", district_id: "50", name: "Barkal", bn_name: "বরকল" },
  { id: "388", district_id: "50", name: "Belaichhari", bn_name: "বিলাইছড়ি" },
  { id: "389", district_id: "50", name: "Juraichhari", bn_name: "জুরাছড়ি" },
  { id: "390", district_id: "50", name: "Kaptai", bn_name: "কাপ্তাই" },
  { id: "391", district_id: "50", name: "Kawkhali", bn_name: "কাউখালী" },
  { id: "392", district_id: "50", name: "Langadu", bn_name: "লংগদু" },
  { id: "393", district_id: "50", name: "Naniarchar", bn_name: "নানিয়ারচর" },
  { id: "394", district_id: "50", name: "Rajasthali", bn_name: "রাজস্থলী" },
  { id: "395", district_id: "50", name: "Rangamati Sadar", bn_name: "রাঙ্গামাটি সদর" },

  // Habiganj (ID: 51)
  { id: "396", district_id: "51", name: "Ajmiriganj", bn_name: "আজমিরীগঞ্জ" },
  { id: "397", district_id: "51", name: "Bahubal", bn_name: "বাহুবল" },
  { id: "398", district_id: "51", name: "Baniachong", bn_name: "বানিয়াচং" },
  { id: "399", district_id: "51", name: "Chunarughat", bn_name: "চুনারুঘাট" },
  { id: "400", district_id: "51", name: "Habiganj Sadar", bn_name: "হবিগঞ্জ সদর" },
  { id: "401", district_id: "51", name: "Lakhai", bn_name: "লাখাই" },
  { id: "402", district_id: "51", name: "Madhabpur", bn_name: "মাধবপুর" },
  { id: "403", district_id: "51", name: "Nabiganj", bn_name: "নবীগঞ্জ" },
  { id: "404", district_id: "51", name: "Sayestaganj", bn_name: "শায়েস্তাগঞ্জ" },

  // Maulvibazar (ID: 52)
  { id: "405", district_id: "52", name: "Barlekha", bn_name: "বড়লেখা" },
  { id: "406", district_id: "52", name: "Juri", bn_name: "জুড়ী" },
  { id: "407", district_id: "52", name: "Kamalganj", bn_name: "কমলগঞ্জ" },
  { id: "408", district_id: "52", name: "Kulaura", bn_name: "কুলাউড়া" },
  { id: "409", district_id: "52", name: "Maulvibazar Sadar", bn_name: "মৌলভীবাজার সদর" },
  { id: "410", district_id: "52", name: "Rajnagar", bn_name: "রাজনগর" },
  { id: "411", district_id: "52", name: "Sreemangal", bn_name: "শ্রীমঙ্গল" },

  // Sunamganj (ID: 53)
  { id: "412", district_id: "53", name: "Bishwamvarpur", bn_name: "বিশ্বম্ভরপুর" },
  { id: "413", district_id: "53", name: "Chhatak", bn_name: "ছাতক" },
  { id: "414", district_id: "53", name: "Dharampasha", bn_name: "ধর্মপাশা" },
  { id: "415", district_id: "53", name: "Dirai", bn_name: "দিরাই" },
  { id: "416", district_id: "53", name: "Dowarabazar", bn_name: "দোয়ারাবাজার" },
  { id: "417", district_id: "53", name: "Jagannathpur", bn_name: "জগন্নাথপুর" },
  { id: "418", district_id: "53", name: "Jamalganj", bn_name: "জামালগঞ্জ" },
  { id: "419", district_id: "53", name: "Madhyanagar", bn_name: "মধ্যনগর" },
  { id: "420", district_id: "53", name: "Shanthiganj", bn_name: "শান্তিগঞ্জ" },
  { id: "421", district_id: "53", name: "Sulla", bn_name: "শাল্লা" },
  { id: "422", district_id: "53", name: "Sunamganj Sadar", bn_name: "সুনামগঞ্জ সদর" },
  { id: "423", district_id: "53", name: "Tahirpur", bn_name: "তাহিরপুর" },

  // Sylhet (ID: 54)
  { id: "424", district_id: "54", name: "Balaganj", bn_name: "বালাগঞ্জ" },
  { id: "425", district_id: "54", name: "Beanibazar", bn_name: "বিয়ানীবাজার" },
  { id: "426", district_id: "54", name: "Bishwanath", bn_name: "বিশ্বনাথ" },
  { id: "427", district_id: "54", name: "Companiganj", bn_name: "কোম্পানীগঞ্জ" },
  { id: "428", district_id: "54", name: "Dakshin Surma", bn_name: "দক্ষিণ সুরমা" },
  { id: "429", district_id: "54", name: "Fenchuganj", bn_name: "ফেঞ্চুগঞ্জ" },
  { id: "430", district_id: "54", name: "Golapganj", bn_name: "গোলাপগঞ্জ" },
  { id: "431", district_id: "54", name: "Gowainghat", bn_name: "গোয়াইনঘাট" },
  { id: "432", district_id: "54", name: "Jaintiapur", bn_name: "জৈন্তাপুর" },
  { id: "433", district_id: "54", name: "Kanaighat", bn_name: "কানাইঘাট" },
  { id: "434", district_id: "54", name: "Osmani Nagar", bn_name: "ওসমানী নগর" },
  { id: "435", district_id: "54", name: "Sylhet Sadar", bn_name: "সিলেট সদর" },
  { id: "436", district_id: "54", name: "Zakiganj", bn_name: "জকিগঞ্জ" },

  // Bagerhat (ID: 55)
  { id: "437", district_id: "55", name: "Bagerhat Sadar", bn_name: "বাগেরহাট সদর" },
  { id: "438", district_id: "55", name: "Chitalmari", bn_name: "চিতলমারী" },
  { id: "439", district_id: "55", name: "Fakirhat", bn_name: "ফকিরহাট" },
  { id: "440", district_id: "55", name: "Kachua", bn_name: "কচুয়া" },
  { id: "441", district_id: "55", name: "Mollahat", bn_name: "মোল্লাহাট" },
  { id: "442", district_id: "55", name: "Mongla", bn_name: "মোংলা" },
  { id: "443", district_id: "55", name: "Morrelganj", bn_name: "মোড়েলগঞ্জ" },
  { id: "444", district_id: "55", name: "Rampal", bn_name: "রামপাল" },
  { id: "445", district_id: "55", name: "Sarankhola", bn_name: "শরণখোলা" },

  // Chuadanga (ID: 56)
  { id: "446", district_id: "56", name: "Alamdanga", bn_name: "আলমডাঙ্গা" },
  { id: "447", district_id: "56", name: "Chuadanga Sadar", bn_name: "চুয়াডাঙ্গা সদর" },
  { id: "448", district_id: "56", name: "Damurhuda", bn_name: "দামুড়হুদা" },
  { id: "449", district_id: "56", name: "Jibannagar", bn_name: "জীবননগর" },

  // Jashore (ID: 57)
  { id: "450", district_id: "57", name: "Abhaynagar", bn_name: "অভয়নগর" },
  { id: "451", district_id: "57", name: "Bagherpara", bn_name: "বাঘারপাড়া" },
  { id: "452", district_id: "57", name: "Chaugachha", bn_name: "চৌগাছা" },
  { id: "453", district_id: "57", name: "Jashore Sadar", bn_name: "যশোর সদর" },
  { id: "454", district_id: "57", name: "Jhikargachha", bn_name: "ঝিকরগাছা" },
  { id: "455", district_id: "57", name: "Keshabpur", bn_name: "কেশবপুর" },
  { id: "456", district_id: "57", name: "Manirampur", bn_name: "মণিরামপুর" },
  { id: "457", district_id: "57", name: "Sharsha", bn_name: "শার্শা" },

  // Jhenaidah (ID: 58)
  { id: "458", district_id: "58", name: "Harinakunda", bn_name: "হরিণাকুণ্ডু" },
  { id: "459", district_id: "58", name: "Jhenaidah Sadar", bn_name: "ঝিনাইদহ সদর" },
  { id: "460", district_id: "58", name: "Kaliganj", bn_name: "কালীগঞ্জ" },
  { id: "461", district_id: "58", name: "Kotchandpur", bn_name: "কোটচাঁদপুর" },
  { id: "462", district_id: "58", name: "Maheshpur", bn_name: "মহেশপুর" },
  { id: "463", district_id: "58", name: "Shailkupa", bn_name: "শৈলকুপা" },

  // Khulna (ID: 59)
  { id: "464", district_id: "59", name: "Batiaghata", bn_name: "বটিয়াঘাটা" },
  { id: "465", district_id: "59", name: "Dacope", bn_name: "দাকোপ" },
  { id: "466", district_id: "59", name: "Dumuria", bn_name: "ডুমুরিয়া" },
  { id: "467", district_id: "59", name: "Dighalia", bn_name: "দিঘলিয়া" },
  { id: "468", district_id: "59", name: "Koyra", bn_name: "কয়রা" },
  { id: "469", district_id: "59", name: "Paikgachha", bn_name: "পাইকগাছা" },
  { id: "470", district_id: "59", name: "Phultala", bn_name: "ফুলতলা" },
  { id: "471", district_id: "59", name: "Rupsha", bn_name: "রূপসা" },
  { id: "472", district_id: "59", name: "Terokhada", bn_name: "তেরখাদা" },

  // Kushtia (ID: 60)
  { id: "473", district_id: "60", name: "Bheramara", bn_name: "ভেড়ামারা" },
  { id: "474", district_id: "60", name: "Daulatpur", bn_name: "দৌলতপুর" },
  { id: "475", district_id: "60", name: "Khoksa", bn_name: "খোকসা" },
  { id: "476", district_id: "60", name: "Kumarkhali", bn_name: "কুমারখালী" },
  { id: "477", district_id: "60", name: "Kushtia Sadar", bn_name: "কুষ্টিয়া সদর" },
  { id: "478", district_id: "60", name: "Mirpur", bn_name: "মিরপুর" },

  // Magura (ID: 61)
  { id: "479", district_id: "61", name: "Magura Sadar", bn_name: "মাগুরা সদর" },
  { id: "480", district_id: "61", name: "Mohammadpur", bn_name: "মহম্মদপুর" },
  { id: "481", district_id: "61", name: "Shalikha", bn_name: "শালিখা" },
  { id: "482", district_id: "61", name: "Sreepur", bn_name: "শ্রীপুর" },

  // Meherpur (ID: 62)
  { id: "483", district_id: "62", name: "Gangni", bn_name: "গাংনী" },
  { id: "484", district_id: "62", name: "Meherpur Sadar", bn_name: "মেহেরপুর সদর" },
  { id: "485", district_id: "62", name: "Mujibnagar", bn_name: "মুজিবনগর" },

  // Narail (ID: 63)
  { id: "486", district_id: "63", name: "Kalia", bn_name: "কালিয়া" },
  { id: "487", district_id: "63", name: "Lohagara", bn_name: "লোহাগড়া" },
  { id: "488", district_id: "63", name: "Narail Sadar", bn_name: "নড়াইল সদর" },

  // Satkhira (ID: 64)
  { id: "489", district_id: "64", name: "Assasuni", bn_name: "আশাশুনি" },
  { id: "490", district_id: "64", name: "Debhata", bn_name: "দেবহাটা" },
  { id: "491", district_id: "64", name: "Kalaroa", bn_name: "কলারোয়া" },
  { id: "492", district_id: "64", name: "Kaliganj", bn_name: "কালীগঞ্জ" },
  { id: "493", district_id: "64", name: "Satkhira Sadar", bn_name: "সাতক্ষীরা সদর" },
  { id: "494", district_id: "64", name: "Shyamnagar", bn_name: "শ্যামনগর" },
  { id: "495", district_id: "64", name: "Tala", bn_name: "তালা" },

  // ==========================================
  // METROPOLITAN POLICE STATIONS & NEW THANAS
  // ==========================================

  // Dhaka Metropolitan Police (DMP) - ID: 65
  { id: "496", district_id: "65", name: "Adabor", bn_name: "আদাবর" },
  { id: "497", district_id: "65", name: "Airport", bn_name: "বিমানবন্দর" },
  { id: "498", district_id: "65", name: "Badda", bn_name: "বাড্ডা" },
  { id: "499", district_id: "65", name: "Banani", bn_name: "বনানী" },
  { id: "500", district_id: "65", name: "Bangshal", bn_name: "বংশাল" },
  { id: "501", district_id: "65", name: "Bhashantek", bn_name: "ভাষানটেক" },
  { id: "502", district_id: "65", name: "Bhatara", bn_name: "ভাটারা" },
  { id: "503", district_id: "65", name: "Cantonment", bn_name: "ক্যান্টনমেন্ট" },
  { id: "504", district_id: "65", name: "Chawkbazar", bn_name: "চকবাজার" },
  { id: "505", district_id: "65", name: "Dakshinkhan", bn_name: "দক্ষিণখান" },
  { id: "506", district_id: "65", name: "Darus Salam", bn_name: "দারুস সালাম" },
  { id: "507", district_id: "65", name: "Demra", bn_name: "ডেমরা" },
  { id: "508", district_id: "65", name: "Dhanmondi", bn_name: "ধানমন্ডি" },
  { id: "509", district_id: "65", name: "Gendaria", bn_name: "গেন্ডারিয়া" },
  { id: "510", district_id: "65", name: "Gulshan", bn_name: "গুলশান" },
  { id: "511", district_id: "65", name: "Hatirjheel", bn_name: "হাতিরঝিল" },
  { id: "512", district_id: "65", name: "Hazaribagh", bn_name: "হাজারীবাগ" },
  { id: "513", district_id: "65", name: "Jatrabari", bn_name: "যাত্রাবাড়ী" },
  { id: "514", district_id: "65", name: "Kadamtali", bn_name: "কদমতলী" },
  { id: "515", district_id: "65", name: "Kafrul", bn_name: "কাফরুল" },
  { id: "516", district_id: "65", name: "Kalabagan", bn_name: "কলাবাগান" },
  { id: "517", district_id: "65", name: "Kamrangirchar", bn_name: "কামরাঙ্গীরচর" },
  { id: "518", district_id: "65", name: "Khilgaon", bn_name: "খিলগাঁও" },
  { id: "519", district_id: "65", name: "Khilkhet", bn_name: "খিলক্ষেত" },
  { id: "520", district_id: "65", name: "Kotwali", bn_name: "কোতোয়ালী" },
  { id: "521", district_id: "65", name: "Lalbagh", bn_name: "লালবাগ" },
  { id: "522", district_id: "65", name: "Mirpur", bn_name: "মিরপুর" },
  { id: "523", district_id: "65", name: "Mohammadpur", bn_name: "মোহাম্মদপুর" },
  { id: "524", district_id: "65", name: "Motijheel", bn_name: "মতিঝিল" },
  { id: "525", district_id: "65", name: "Mugda", bn_name: "মুগদা" },
  { id: "526", district_id: "65", name: "New Market", bn_name: "নিউ মার্কেট" },
  { id: "527", district_id: "65", name: "Pallabi", bn_name: "পল্লবী" },
  { id: "528", district_id: "65", name: "Paltan", bn_name: "পল্টন" },
  { id: "529", district_id: "65", name: "Ramna", bn_name: "রমনা" },
  { id: "530", district_id: "65", name: "Rampura", bn_name: "রামপুরা" },
  { id: "531", district_id: "65", name: "Rupnagar", bn_name: "রূপনগর" },
  { id: "532", district_id: "65", name: "Sabujbagh", bn_name: "সবুজবাগ" },
  { id: "533", district_id: "65", name: "Shah Ali", bn_name: "শাহ আলী" },
  { id: "534", district_id: "65", name: "Shahbagh", bn_name: "শাহবাগ" },
  { id: "535", district_id: "65", name: "Shajahanpur", bn_name: "শাহজাহানপুর" },
  { id: "536", district_id: "65", name: "Sher-e-Bangla Nagar", bn_name: "শেরেবাংলা নগর" },
  { id: "537", district_id: "65", name: "Shyampur", bn_name: "শ্যামপুর" },
  { id: "538", district_id: "65", name: "Sutrapur", bn_name: "সূত্রাপুর" },
  { id: "539", district_id: "65", name: "Tejgaon", bn_name: "তেজগাঁও" },
  { id: "540", district_id: "65", name: "Tejgaon Industrial", bn_name: "তেজগাঁও শিল্পাঞ্চল" },
  { id: "541", district_id: "65", name: "Turag", bn_name: "তুরাগ" },
  { id: "542", district_id: "65", name: "Uttara East", bn_name: "উত্তরা পূর্ব" },
  { id: "543", district_id: "65", name: "Uttara West", bn_name: "উত্তরা পশ্চিম" },
  { id: "544", district_id: "65", name: "Uttarkhan", bn_name: "উত্তরখান" },
  { id: "545", district_id: "65", name: "Wari", bn_name: "ওয়ারী" },

  // Chattogram Metropolitan Police (CMP) - District ID: 43
  { id: "546", district_id: "43", name: "Akbar Shah", bn_name: "আকবর শাহ" },
  { id: "547", district_id: "43", name: "Bakalia", bn_name: "বাকলিয়া" },
  { id: "548", district_id: "43", name: "Bandar", bn_name: "বন্দর" },
  { id: "549", district_id: "43", name: "Bayazid Bostami", bn_name: "বায়েজিদ বোস্তামী" },
  { id: "550", district_id: "43", name: "Chandgaon", bn_name: "চান্দগাঁও" },
  { id: "551", district_id: "43", name: "Chawkbazar", bn_name: "চকবাজার" },
  { id: "552", district_id: "43", name: "Double Mooring", bn_name: "ডবলমুরিং" },
  { id: "553", district_id: "43", name: "EPZ", bn_name: "ইপিজেড" },
  { id: "554", district_id: "43", name: "Halishahar", bn_name: "হালিশহর" },
  { id: "555", district_id: "43", name: "Khulshi", bn_name: "খুলশী" },
  { id: "556", district_id: "43", name: "Kotwali (CMP)", bn_name: "কোতোয়ালী" },
  { id: "557", district_id: "43", name: "Pahartali", bn_name: "পাহাড়তলী" },
  { id: "558", district_id: "43", name: "Panchlaish", bn_name: "পাঁচলাইশ" },
  { id: "559", district_id: "43", name: "Patenga", bn_name: "পতেঙ্গা" },
  { id: "560", district_id: "43", name: "Sadarghat", bn_name: "সদরঘাট" },

  // Rajshahi Metropolitan Police (RMP) - District ID: 24
  { id: "561", district_id: "24", name: "Airport (RMP)", bn_name: "বিমানবন্দর" },
  { id: "562", district_id: "24", name: "Belpukur", bn_name: "বেলপুকুর" },
  { id: "563", district_id: "24", name: "Boalia", bn_name: "বোয়ালিয়া" },
  { id: "564", district_id: "24", name: "Chandrima", bn_name: "চন্দ্রিমা" },
  { id: "565", district_id: "24", name: "Damkura", bn_name: "দামকুড়া" },
  { id: "566", district_id: "24", name: "Karnahar", bn_name: "কর্ণহার" },
  { id: "567", district_id: "24", name: "Kashiadanga", bn_name: "কাশিয়াডাঙ্গা" },
  { id: "568", district_id: "24", name: "Katakhali", bn_name: "কাটাখালী" },
  { id: "569", district_id: "24", name: "Matihar", bn_name: "মতিহার" },
  { id: "570", district_id: "24", name: "Rajpara", bn_name: "রাজপাড়া" },
  { id: "571", district_id: "24", name: "Shah Makhdum", bn_name: "শাহ মখদুম" },

  // Khulna Metropolitan Police (KMP) - District ID: 59
  { id: "572", district_id: "59", name: "Arongghata", bn_name: "আড়ংঘাটা" },
  { id: "573", district_id: "59", name: "Daulatpur (KMP)", bn_name: "দৌলতপুর" },
  { id: "574", district_id: "59", name: "Harintana", bn_name: "হরিণটানা" },
  { id: "575", district_id: "59", name: "Khalishpur", bn_name: "খালিশপুর" },
  { id: "576", district_id: "59", name: "Khan Jahan Ali", bn_name: "খানজাহান আলী" },
  { id: "577", district_id: "59", name: "Khulna Sadar", bn_name: "খুলনা সদর" },
  { id: "578", district_id: "59", name: "Labanchara", bn_name: "লবণচরা" },
  { id: "579", district_id: "59", name: "Sonadanga", bn_name: "সোনাডাঙ্গা" },

  // Sylhet Metropolitan Police (SMP) - District ID: 54
  { id: "580", district_id: "54", name: "Airport (SMP)", bn_name: "বিমানবন্দর" },
  { id: "581", district_id: "54", name: "Jalalabad", bn_name: "জালালাবাদ" },
  { id: "582", district_id: "54", name: "Kotwali (SMP)", bn_name: "কোতোয়ালী" },
  { id: "583", district_id: "54", name: "Mogla Bazar", bn_name: "মোগলা বাজার" },
  { id: "584", district_id: "54", name: "Shah Paran", bn_name: "শাহপরাণ" },

  // Barishal Metropolitan Police (BMP) - District ID: 35
  { id: "585", district_id: "35", name: "Airport (BMP)", bn_name: "বিমানবন্দর" },
  { id: "586", district_id: "35", name: "Bandar (BMP)", bn_name: "বন্দর" },
  { id: "587", district_id: "35", name: "Kaunia", bn_name: "কাউনিয়া" },
  { id: "588", district_id: "35", name: "Kotwali (BMP)", bn_name: "কোতোয়ালী" },

  // Rangpur Metropolitan Police (RpMP) - District ID: 32
  { id: "589", district_id: "32", name: "Haragach", bn_name: "হারাগাছ" },
  { id: "590", district_id: "32", name: "Hazirhat", bn_name: "হাজীরহাট" },
  { id: "591", district_id: "32", name: "Kotwali (RpMP)", bn_name: "কোতোয়ালী" },
  { id: "592", district_id: "32", name: "Mahiganj", bn_name: "মাহিগঞ্জ" },
  { id: "593", district_id: "32", name: "Parshuram", bn_name: "পরশুরাম" },
  { id: "594", district_id: "32", name: "Tajhat", bn_name: "তাজহাট" },

  // Gazipur Metropolitan Police (GMP) - District ID: 3
  { id: "595", district_id: "3", name: "Bason", bn_name: "বাসন" },
  { id: "596", district_id: "3", name: "Gacha", bn_name: "গাছা" },
  { id: "597", district_id: "3", name: "Kashimpur", bn_name: "কাশিমপুর" },
  { id: "598", district_id: "3", name: "Konabari", bn_name: "কোনাবাড়ী" },
  { id: "599", district_id: "3", name: "Pubail", bn_name: "পূবাইল" },
  { id: "600", district_id: "3", name: "Sadar (GMP)", bn_name: "সদর" },
  { id: "601", district_id: "3", name: "Tongi East", bn_name: "টঙ্গী পূর্ব" },
  { id: "602", district_id: "3", name: "Tongi West", bn_name: "টঙ্গী পশ্চিম" },

  // Additional District Police Thanas (Newly formed / specific regional units)
  { id: "603", district_id: "45", name: "Shampur (Cox's)", bn_name: "শ্যামপুর" },
  { id: "604", district_id: "44", name: "Sadar South (Cumilla)", bn_name: "সদর দক্ষিণ" },
  { id: "605", district_id: "44", name: "Sadar North (Cumilla)", bn_name: "সদর উত্তর" },
  { id: "606", district_id: "1", name: "Ashulia", bn_name: "আশুলিয়া" },
  { id: "607", district_id: "1", name: "Keraniganj Model", bn_name: "কেরানীগঞ্জ মডেল" },
  { id: "608", district_id: "1", name: "South Keraniganj", bn_name: "দক্ষিণ কেরানীগঞ্জ" },
  { id: "609", district_id: "11", name: "Fatullah", bn_name: "ফতুল্লা" },
  { id: "610", district_id: "11", name: "Siddhirganj", bn_name: "সিদ্ধিরগঞ্জ" },
  { id: "611", district_id: "12", name: "Madhabdi", bn_name: "মাধবদী" },
  { id: "612", district_id: "42", name: "Faridganj South", bn_name: "ফরিদগঞ্জ দক্ষিণ" },
  { id: "613", district_id: "31", name: "Ruhea", bn_name: "রুহিয়া" },
  { id: "614", district_id: "33", name: "Bhulli", bn_name: "ভুল্লী" },
  { id: "615", district_id: "49", name: "Bhasan Char", bn_name: "ভাসানচর" },
  { id: "616", district_id: "49", name: "Char Jabbar", bn_name: "চর জব্বার" },
  { id: "617", district_id: "18", name: "Shahjahanpur (Bogura)", bn_name: "শাহজাহানপুর" },
  { id: "618", district_id: "48", name: "Chandraganj", bn_name: "চন্দ্রগঞ্জ" },
  { id: "619", district_id: "40", name: "Padma", bn_name: "পদ্মা" },
  { id: "620", district_id: "47", name: "Sajek", bn_name: "সাজেক" },
  { id: "621", district_id: "50", name: "Chandraghona", bn_name: "চন্দ্রঘোনা" },
  { id: "622", district_id: "41", name: "Katiadi Model", bn_name: "কটিয়াদী মডেল" },
  { id: "623", district_id: "6", name: "Kishoreganj Model", bn_name: "কিশোরগঞ্জ মডেল" },
  { id: "624", district_id: "17", name: "Bangabandhu Setu East", bn_name: "বঙ্গবন্ধু সেতু পূর্ব" },
  { id: "625", district_id: "25", name: "Bangabandhu Setu West", bn_name: "বঙ্গবন্ধু সেতু পশ্চিম" },
  { id: "626", district_id: "25", name: "Salanga", bn_name: "সলঙ্গা" },
  { id: "627", district_id: "25", name: "Enayetpur", bn_name: "এনায়েতপুর" },
  { id: "628", district_id: "5", name: "Bahadurabad", bn_name: "বাহাদুরাবাদ" },
  { id: "629", district_id: "23", name: "Aminpur", bn_name: "আমিনপুর" },
  { id: "630", district_id: "10", name: "Pagla", bn_name: "পাগলা" },
  { id: "631", district_id: "13", name: "Barhatta Model", bn_name: "বরহাট্টা মডেল" },
  { id: "632", district_id: "35", name: "Kazirhat", bn_name: "কাজিরহাট" },
  { id: "633", district_id: "36", name: "Sashibhusan", bn_name: "শশীভূষণ" },
  { id: "634", district_id: "36", name: "Dularhat", bn_name: "দুলারহাট" },
  { id: "635", district_id: "36", name: "South Aicha", bn_name: "দক্ষিণ আইচা" },
  { id: "636", district_id: "38", name: "Mohipur", bn_name: "মহিপুর" },
  { id: "637", district_id: "34", name: "Taltali Model", bn_name: "তালতলী মডেল" },
  { id: "638", district_id: "15", name: "Sakhipur (Shariatpur)", bn_name: "সখিপুর" },
  { id: "639", district_id: "15", name: "Padma Bridge South", bn_name: "পদ্মা সেতু দক্ষিণ" }
];

export const UPAZILA_OPTIONS = THANA_OPTIONS;


// Helper functions
export const getDivisionById = (divisionId) => DIVISION_OPTIONS.find(div => div.id === divisionId);
export const getDistrictById = (districtId) => DISTRICT_OPTIONS.find(dist => dist.id === districtId);
export const getDistrictsByDivision = (divisionId) => DISTRICT_OPTIONS.filter(dist => dist.division_id === divisionId);
export const getUpazilasByDistrict = (districtId) => {
  // Return all thanas/upazilas for the given district ID
  return THANA_OPTIONS.filter(t => t.district_id === districtId);
};

